version: "3.5"
 
services:
  service-bus:
    #image: rabbitmq:latest
    image: rabbitmq:3.8.13-management
    container_name: bus-service-test
    #restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
    - 5682:5672
    - 15682:15672
    networks:
    - aforo255-test  
  service-consult:
    image: consul:1.9.10
    container_name: consult-service-test
    #restart: always
    ports:
    - 8510:8500
    networks:
    - aforo255-test
  service-balancer:
    image: fabiolb/fabio:1.5.15-go1.15.5
    container_name: balancer-service-test
    #restart: always
    environment:
    - FABIO_REGISTRY_CONSUL_ADDR=consult-service-test:8500 
    ports:
    - 9900:9998
    - 9901:9999
    networks:
    - aforo255-test
    depends_on:
    - service-consult
  service-config:
    image: nacos/nacos-server:v2.0.3
    container_name: config-service-test
    #restart: always
    environment:
    - MODE=standalone
    ports:
    - 8858:8848
    networks:
    - aforo255-test

networks:
  aforo255-test:
    name: aforo255-test